apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-flask-deployment
  namespace: hello
spec:
  replicas: 5
  selector:
    matchLabels:
      app: hello-flask
  template:
    metadata:
      labels:
        app: hello-flask
    spec:
      containers:
      - name: hello-flask
        image: stradivirus/hello
        ports:
        - containerPort: 5000
